name: Build and test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: 'Install'
        run: npm ci
      - name: 'Lint'
        run: npm run lint
      - name: 'Build'
        run: npm run build:release
      - name: 'Test'
        run: npm run test
